# Clean ARTISTS

In [96]:
import spotify2musicbrainz as mbSpot
from difflib import SequenceMatcher
import pandas as pd
from dbhelper import DatabaseHelper

db_uri = "postgresql://musicbrainz:musicbrainz@localhost:5432/musicbrainz_db"
stg_uri = "postgresql://myuser:mypass@localhost:5432/gig_stagingdb"

_db = DatabaseHelper(db_uri)
_dw = DatabaseHelper(stg_uri)

In [78]:
origin_df = _dw.extract_query_to_pandas('select * from public."dim.artists"')
df = origin_df[origin_df["is_active"] == True]
df['sort_name'] = df.sort_name.apply(lambda x : x.lower().replace(' ', '_').replace(',', '').strip())

C:\Users\DeRossiConsulting2\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,id,gid,name,sort_name,type,area,gender,is_active
0,1,89ad4ac3-39f7-470e-963a-56509c546377,Various Artists,Various Artists,3.0,3.0,3.0,True
1,2,c06aa285-520e-40c0-b776-83d2c9e8a6d1,Deleted Artist,Deleted Artist,0.0,0.0,0.0,True
2,4,10adbe5e-a2c0-4bf3-8249-2b4cbf6e6ca8,Massive Attack,Massive Attack,2.0,2.0,2.0,True
3,6,ea738cc5-5b1a-44a4-94ab-ed0c1bd71ecf,Apartment 26,Apartment 26,2.0,2.0,2.0,False
4,7,025d1400-5420-4fc8-a482-2b59096fd22c,Dr. Evil,Dr. Evil,4.0,4.0,4.0,True

In [79]:
df.head()

,id,gid,name,sort_name,type,area,gender,is_active
0,1,89ad4ac3-39f7-470e-963a-56509c546377,Various Artists,various_artists,3.0,3.0,3.0,True
1,2,c06aa285-520e-40c0-b776-83d2c9e8a6d1,Deleted Artist,deleted_artist,0.0,0.0,0.0,True
2,4,10adbe5e-a2c0-4bf3-8249-2b4cbf6e6ca8,Massive Attack,massive_attack,2.0,2.0,2.0,True
4,7,025d1400-5420-4fc8-a482-2b59096fd22c,Dr. Evil,dr._evil,4.0,4.0,4.0,True
5,8,a1c091c6-13f5-4ef5-8ccb-beda9f57956b,Torley Wong,wong_torley,1.0,1.0,1.0,True

In [74]:
import numpy as np
def levenshtein_ratio_and_distance(s, t, ratio_calc = False):
    """ levenshtein_ratio_and_distance:
        Calculates levenshtein distance between two strings.
        If ratio_calc = True, the function computes the
        levenshtein distance ratio of similarity between two strings
        For all i and j, distance[i,j] will contain the Levenshtein
        distance between the first i characters of s and the
        first j characters of t
    """
    # Initialize matrix of zeros
    rows = len(s)+1
    cols = len(t)+1
    distance = np.zeros((rows,cols),dtype = int)

    # Populate matrix of zeros with the indeces of each character of both strings
    for i in range(1, rows):
        for k in range(1,cols):
            distance[i][0] = i
            distance[0][k] = k

    # Iterate over the matrix to compute the cost of deletions,insertions and/or substitutions    
    for col in range(1, cols):
        for row in range(1, rows):
            if s[row-1] == t[col-1]:
                cost = 0 # If the characters are the same in the two strings in a given position [i,j] then the cost is 0
            else:
                # In order to align the results with those of the Python Levenshtein package, if we choose to calculate the ratio
                # the cost of a substitution is 2. If we calculate just distance, then the cost of a substitution is 1.
                if ratio_calc == True:
                    cost = 2
                else:
                    cost = 1
            distance[row][col] = min(distance[row-1][col] + 1,      # Cost of deletions
                                 distance[row][col-1] + 1,          # Cost of insertions
                                 distance[row-1][col-1] + cost)     # Cost of substitutions
    if ratio_calc == True:
        # Computation of the Levenshtein Distance Ratio
        Ratio = ((len(s)+len(t)) - distance[row][col]) / (len(s)+len(t))
        return Ratio
    else:
        # print(distance) # Uncomment if you want to see the matrix showing how the algorithm computes the cost of deletions,
        # insertions and/or substitutions
        # This is the minimum number of edits needed to convert string a to string b
        return "The strings are {} edits away".format(distance[row][col])

In [12]:
def get_Artist_mbid(df_artist):
    ls_mbid=[]
    for index, row in df_artist.iterrows(): 
        ls_mbid.append(mbSpot.get_artist_mbid(row['id']))
        
    return ls_mbid

def get_spot_mbid(spotify_id):
    return mbSpot.get_artist_mbid(spotify_id)

def get_mbid(artist_title):
    artist = df[df['name'] == artist_title]
    if (artist.empty):
        norm_artist = artist_title.lower().replace(' ', '_').replace(',', '').strip()
        artist = df[df['sort_name'] == norm_artist]
    return artist['gid']

In [111]:
events = pd.read_csv('../datasets/ukEvents.csv')
top_200 = pd.read_csv('../datasets/spotify_top_200_weekly.csv')
top_200_details = pd.read_csv('../datasets/spotify_track_details.csv')
top_tracks = pd.read_csv('../datasets/spotify_track_details.csv')

#my_df = pd.merge(left = top_200 , right = top_tracks, left_on = 'spotify_id', right_on = 'track_spotifyID')
top_200_details.head()

,track_spotifyID,artist_spotifyID,artist_mbid,artist_name,track_url,track_popularity,track_duration_ms,track_is_local,albumID,album_track_number,album_release_date,album_type
0,2TIlqbIneP0ZY1O0EzYLlc,4GNC7GD6oZMSxPGyXy4MNB,526aab94-697f-44a9-b630-41d1c0505953,Lewis Capaldi,https://open.spotify.com/track/2TIlqbIneP0ZY1O...,82,182160,False,0NVQ9k3wKmuK6T02lLMl6y,3,2018-11-08,single
1,4kV4N9D1iKVxx1KLvtTpjS,66CXWjxzNUsdJxJ2JdwvnR,f4fdbb4c-e4b7-47a0-b83b-d91bbfcfa387,Ariana Grande,https://open.spotify.com/track/4kV4N9D1iKVxx1K...,81,190440,False,2fYhqwDWXjbpjaIJPEfKFw,12,2019-02-08,album
2,5itOtNx0WxtJmi1TQ3RuRd,7CajNmpbOovFoOoasH2HaY,8dd98bdc-80ec-4e93-8509-2f46bafc09a7,Calvin Harris,https://open.spotify.com/track/5itOtNx0WxtJmi1...,80,229184,False,4PwXTHenZZx7ebgsnTM65K,1,2019-01-11,single
3,5itOtNx0WxtJmi1TQ3RuRd,4f9iBmdUOhQWeP7dcAn1pf,NaN,Rag'n'Bone Man,https://open.spotify.com/track/5itOtNx0WxtJmi1...,80,229184,False,4PwXTHenZZx7ebgsnTM65K,1,2019-01-11,single
4,6ocbgoVGwYJhOv1GgI9NsF,66CXWjxzNUsdJxJ2JdwvnR,f4fdbb4c-e4b7-47a0-b83b-d91bbfcfa387,Ariana Grande,https://open.spotify.com/track/6ocbgoVGwYJhOv1...,87,178626,False,2fYhqwDWXjbpjaIJPEfKFw,10,2019-02-08,album

In [16]:
missing_artists = top_200_details[top_200_details["artist_mbid"].isnull()]
missing_artists.head()

,track_spotifyID,artist_spotifyID,artist_mbid,artist_name,track_url,track_popularity,track_duration_ms,track_is_local,albumID,album_track_number,album_release_date,album_type
3,5itOtNx0WxtJmi1TQ3RuRd,4f9iBmdUOhQWeP7dcAn1pf,NaN,Rag'n'Bone Man,https://open.spotify.com/track/5itOtNx0WxtJmi1...,80,229184,False,4PwXTHenZZx7ebgsnTM65K,1,2019-01-11,single
11,2VxeLyX666F8uXCJ0dZF8B,4VIvfOurcf0vuLRxLkGnIG,NaN,Bradley Cooper,https://open.spotify.com/track/2VxeLyX666F8uXC...,86,215733,False,4sLtOBOzn4s3GDUv3c5oJD,12,2018-10-05,album
12,2cytBOLpwFRX7J9URCrFIe,31Ua7zSTJxegjyd49ujbSA,NaN,NSG,https://open.spotify.com/track/2cytBOLpwFRX7J9...,69,240081,False,35MvbFXqp1ESDkKNqYfOIM,1,2018-11-30,single
13,2cytBOLpwFRX7J9URCrFIe,7b79bQFziJFedJb75k6hFt,NaN,Tion Wayne,https://open.spotify.com/track/2cytBOLpwFRX7J9...,69,240081,False,35MvbFXqp1ESDkKNqYfOIM,1,2018-11-30,single
30,1fp2uoWXPca3mIdxRHIgQm,1Gm0kKaDx4GH6pQF88rjSK,NaN,Cadet,https://open.spotify.com/track/1fp2uoWXPca3mId...,65,192571,False,4wOuGy0YTmOHjHIUo6drO8,1,2018-09-14,single

## Get Artists MBID By Titles

In [131]:
missing_artists = top_200_details[top_200_details["artist_mbid"].isnull()]
mbids = {}
missings = []
for art in missing_artists['artist_name'].unique():
    mbid = get_mbid(art).values
    if(len(mbid) > 1):
        mbids[art] = mbid[0]
    else :
        missings.append(art)

In [126]:
for index, row in top_200_details[top_200_details["artist_mbid"].isnull()].iterrows():
    if row['artist_name'] in mbids:
        name = row['artist_name']
        #top_200_details.loc[top_200_details.artist_name == 'Bradley Cooper', 'artist_mbid'] = 'cbe7746f-d4b4-4f0d-a435-1aa181d97b1b'
        top_200_details.loc[top_200_details.artist_name == name, 'artist_mbid'] = mbids[name]

In [139]:
len(top_200_details[top_200_details["artist_mbid"].isnull()])

47

In [140]:
top_200_details.to_csv('../datasets/spotify_top_200_weekly_3.csv')

## Get Artists MBID By Similar Titles

In [137]:
for artist in missings:
    artist_splited = artist.split()
    query = "select * from musicbrainz.artist where lower(name) = '" + artist.lower().replace("'" , "") + "'"
    #for itm in artist_splited:
    #    query += " or lower(name) like '%" + itm.lower().replace("'" , "") + "%' "
    similar_artists = _db.extract_query_to_pandas(query)
    for index, row in similar_artists.iterrows():
        name = row['name']
        ratio = levenshtein_ratio_and_distance(artist, name, ratio_calc = True)
        print(query, artist, name, ratio)
        if (ratio > 0.75):
            #print(top_200_details.loc[top_200_details.artist_name == artist])
            top_200_details.loc[top_200_details.artist_name == artist, 'artist_mbid'] = row['gid']
            break

select * from musicbrainz.artist where lower(name) = 'digdat' DigDat Digdat 0.8333333333333334
select * from musicbrainz.artist where lower(name) = 'scouting for girls' Scouting For Girls Scouting for Girls 0.9444444444444444
select * from musicbrainz.artist where lower(name) = 'wizkid' WizKid Wizkid 0.8333333333333334
select * from musicbrainz.artist where lower(name) = 'savo' Sav'o Savo 0.8888888888888888
select * from musicbrainz.artist where lower(name) = 'jaykae' Jaykae JayKae 0.8333333333333334
select * from musicbrainz.artist where lower(name) = 'key!' KEY! Key! 0.5
select * from musicbrainz.artist where lower(name) = 'a touch of class' A Touch Of Class A Touch of Class 0.9375
select * from musicbrainz.artist where lower(name) = 'mc rebecca' Mc Rebecca MC Rebecca 0.9
select * from musicbrainz.artist where lower(name) = 'fred again..' Fred again.. Fred Again.. 0.9166666666666666
select * from musicbrainz.artist where lower(name) = 'bandokay' Bandokay BandoKay 0.875
select * from musicbrainz.artist where lower(name) = 'k camp' K CAMP K Camp 0.5